### ISSUE TITLE
[1.17.1] Can't rejoin world after removing Mining Dims mod

### ISSUE THREAD

**Issue by beautiful-lunatic** [kwpugh/mining_Dimensions#10]
Hi! Since downloading this mod, I have been having issues. I can not open my save file anymore, and it is giving me a "selected datapacks is preventing this world from loading, you can manually fix it or use safe mode"  Pressing the safe mode button doesnt do anything, and If I try to remove the mod and run the save file, it gives me an "invalid player data" message and takes me to the multiplayer section.

I am on a single player world and don't use datapacks. I tried deleting the config file and any other files that have "mining dimensions" name in it, but it still isn't doing anything. Is there anything I can do?

**Comment by kwpugh** [comment]
which version are you using?

**Comment by kwpugh** [comment]
Don't suppose you saw the big warning in red on the website about making a backup?

"WARNING: There are issue with adding/removing mods that add dimensions created via JSON method.  Make a BACKUP of your world before using this mod, because if you later remove it, you may not be able to rejoin the world."

**Comment by beautiful-lunatic** [comment]
> Don't suppose you saw the big warning in red on the website about making a backup?
> 
> "WARNING: There are issue with adding/removing mods that add dimensions created via JSON method. Make a BACKUP of your world before using this mod, because if you later remove it, you may not be able to rejoin the world."

Hi! I am using the most recent file uploaded on curseforge. I also did read the warning but didn't really know what the JSON method was, and if I was installing it via that method (copying and pasting the downloaded file) so I didn't make a back-up. My bad I guess! If there is no real way of fixing it, that's fine!

 I don't know what other files I should be messing around/deleting though.

**Comment by kwpugh** [comment]
Some users have reported that using an NBT editor and removing the mining_dims from the level.dat works, but I have not had luck with that method.

![Screen Shot 2021-10-02 at 10 47 34 AM](https://user-images.githubusercontent.com/8809210/135723553-02671f94-2ecf-40a3-a240-5d94c7e64fdc.png)

**Comment by kwpugh** [comment]
Curious, what did you not like about the mod that you decided to remove it?

**Comment by kwpugh** [comment]
Part of this issue:  https://bugs.mojang.com/browse/MC-197860

I tried the solution just now and it works.


uyp added a comment - 20/Jan/21 6:22 PM
Steps to get the dimensions back before this bug is fixed:
Open level.dat using e.g. https://irath96.github.io/webNBT/
Go to Data -> WorldGenSettings, and delete the dimensions tag

*** Actually, for this mod, just delete the mining_dim tags, leave the vanilla ones alone

**Comment by kwpugh** [comment]
Delete the 5 mining_dim in level.dat and save.  rename the saved file to level.dat and move back into Minecraft folder

![Screen Shot 2021-10-02 at 11 45 36 AM](https://user-images.githubusercontent.com/8809210/135725348-c26e7803-5b8e-4b67-8028-58d1a808caf0.png)

**Comment by kwpugh** [comment]
Looks like the Fabric folks are going to fix this issue.

https://github.com/FabricMC/fabric/pull/2078

**Comment by kwpugh** [comment]
This has been fixed  in the Fabric API since 1.18.2
